baseURL = "https://a98zhang.github.io/"
languageCode = "en-us"
title = "Ashley Zhang"
theme = "ashleyzhang"

[params]
  description = "Ashley Zhang â€” researcher, builder, writer"
  homeTitle = "Ashley Zhang"
  homeTagline = "Applied psychology + computer science. Interested in how people make sense of the social world, and how data can help explain it."
  copyright = "&copy; Ashley Zhang"
  profileImage = "img/profile.jpg"
  favicon = "img/favicon.png"
  resumeURL = "https://github.com/a98zhang/toshare/blob/master/Ashley(Qingyang)%20Zhang%20-%20Resume.pdf"

  [params.social]
  email    = "qingyang.zhang@nyu.edu"
  github   = "https://github.com/a98zhang"
  linkedin = "https://www.linkedin.com/in/ashleyz98/"
  twitter  = "https://twitter.com/ashleyzhang_qy"

[[menu.main]]
name   = "Research"
url    = "/research/"
weight = 1

[[menu.main]]
name   = "Projects"
url    = "/projects/"
weight = 2

[[menu.main]]
name   = "Writing"
url    = "/writing/"
weight = 3

[[menu.main]]
name   = "About"
url    = "/about/"
weight = 4
