baseURL = "https://a98zhang.github.io/"
languageCode = "en-us"
title = "ASHLEY ZHANG Âº†Ê∏ÖÊâ¨"
theme = "hugo-creative-portfolio-theme"


[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "green"
  description = "ASHLEY ZHANG"
  copyright = "&copy;2020 from A to Z"
  sidebarAbout = [
    "Education Data Science üìç Stanford"
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Project"
  url = "project/"
  home = true

  [[params.navlinks]]
  name = "Blog"
  url = "blog/"

  [params.social]
  email         = "q1zhang@stanford.edu"
  twitter       = "https://twitter.com/ashleyzhang_qy"
  linkedin      = "https://www.linkedin.com/in/q1zhang/"
  github        = "https://github.com/a98zhang"

